apiVersion: v1
kind: Service
metadata:
  name: {{ include "dockertest.fullname" . }}
  labels:
    {{- include "dockertest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
     - port: {{ .port }}
       targetPort: {{ .targetPort }}
       protocol: TCP
       name: http
  {{- end }}
  selector:
    {{- include "dockertest.selectorLabels" . | nindent 4 }}
