apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-game-engine-backend.fullname" . }}
  labels:
    {{- include "cloud-game-engine-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
   {{- range .Values.service.ports }}
     - port: {{ .port }}
       targetPort: {{ .targetPort }}
       protocol: {{ .protocol }}
       name: {{ .name }}
  {{- end }}
  selector:
    {{- include "cloud-game-engine-backend.selectorLabels" . | nindent 4 }}
